feat: job update
saritasa-nest/stakater-application pull request #2
Opened 2024-10-27 19:49 UTC by rtest12

### Summary

Task: [USAWS-56](https://saritasa.atlassian.net/browse/USAWS-56)

Add completions, parallelism, ttlSecondsAfterFinished, priorityClassName , initContainers and lifecycle in Job template

2024-10-28 01:37 UTC, kseniyashaydurova requested changes
1. Pls show proofs that your tests work
2. Update backend uSummit project component to use your updated HELM chart and see what job you will have in the result and whether it really works

Pls re-request PR once both conditions would be met

2024-10-28 01:37 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +  {{- $appLabels := include "application.labels" $ | fromYaml }}
Did you check this? Pls show proofs that it works in 3 cases correctly:
1. only appLabels exist
2. only additionalLabels exist
3. both exist

2024-10-28 01:37 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +  {{- $appLabels := include "application.labels" $ | fromYaml }}
Let's specify variables somewhere above after https://github.com/saritasa-nest/stakater-application/blob/feature/job-update/application/templates/job.yaml#L2

2024-10-28 01:37 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +        {{- $image := required (print "Undefined image repo for container '" $name "'") $initContainer.image.repository }}
Let's create snippet from it and use snippet here and below for `containers`

2024-10-28 01:37 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +{{ toYaml . | indent 10 }}
Is it correct indent here?

2024-10-28 01:37 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +{{ toYaml . | indent 10 }}
Is it correct indent here?

2024-11-01 20:36 UTC, rtest12 commented on application/templates/job.yaml
> +{{ toYaml . | indent 10 }}
@kseniyashaydurova 
Yes, you were confused by the incorrect indents around

2024-11-01 20:36 UTC, rtest12 commented on application/templates/job.yaml
> +{{ toYaml . | indent 10 }}
@kseniyashaydurova 
Yes, you were confused by the incorrect indents around

2024-11-01 20:36 UTC, rtest12 commented on application/templates/job.yaml
> +        {{- $image := required (print "Undefined image repo for container '" $name "'") $initContainer.image.repository }}
@kseniyashaydurova 
Done

2024-11-01 20:36 UTC, rtest12 commented on application/templates/job.yaml
> +  {{- $appLabels := include "application.labels" $ | fromYaml }}
@kseniyashaydurova 
Done

2024-11-01 20:37 UTC, rtest12 commented on application/templates/job.yaml
> +  {{- $appLabels := include "application.labels" $ | fromYaml }}
@kseniyashaydurova 
Yes you are right, I added defaults

2024-11-01 20:40 UTC, rtest12 commented
> 1. Pls show proofs that your tests work

@kseniyashaydurova 
Here diff locally generated manifests
![Screenshot from 2024-11-01 23-14-25](https://github.com/user-attachments/assets/ff40b9b5-8700-43bd-8754-6fb95a340559)
![Screenshot from 2024-11-01 23-14-51](https://github.com/user-attachments/assets/a7b76b66-d95c-4292-9d20-cf83010afd5e)
![Screenshot from 2024-11-01 23-15-12](https://github.com/user-attachments/assets/112d5784-0488-46f3-ad4c-ff87a47a4660)

2025-01-23 11:55 UTC, kseniyashaydurova requested changes
Pls proove that you `values-test.yaml` works ok

2025-01-23 11:55 UTC, kseniyashaydurova commented on application/templates/_helpers.tpl
> +{{- $image = printf "%s:%s" $image .image.tag }}
This looks too cryptic and quite hard readable, cause all vars are named in the same way. Can you pls override it to make more readable?

2025-01-23 11:55 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +    {{- toYaml $mergedLabels | nindent 4 }}
Pls add it with the same indent as everything else?

2025-01-23 11:55 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +        {{- toYaml $mergedLabels | nindent 8 }}
The same about indent

2025-01-23 11:55 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +        {{- include "job.image" . | indent 8 }}
I would prefer to see here smth like this if that is possible

```suggestion
        image: {{- include "job.image" . | indent 8 }}
```

2025-01-23 11:55 UTC, kseniyashaydurova commented on application/templates/job.yaml
> +        {{- include "job.image" . | indent 8 }}
The same as above

2025-01-23 11:55 UTC, kseniyashaydurova commented on application/templates/_helpers.tpl
> +{{- $image = required "Undefined image repo for container" .image.repository }}
I don't get why do you raise this error here

2025-03-18 12:58 UTC, rtest12 commented
I'll close both PRs with Stakater since the original Stakater repo has significantly changed. It'll be easier to reopen pr later. Some things have changed, and others were already added by the original developers. During the meeting, we decided that we'll come back to this and implement it a bit later, once we've completed the priority tasks

2025-03-18 13:06 UTC, rtest12 commented
I'll close both PRs with Stakater since the original Stakater repo has significantly changed. It'll be easier to reopen pr later. Some things have changed, and others were already added by the original developers. During the meeting, we decided that we'll come back to this and implement it a bit later, once we've completed the priority tasks

2025-03-18 13:06 UTC, closed without merging